### ISSUE TITLE
crash app

### ISSUE THREAD

**Issue by APakrohk** [marazmista/radeon-profile#144]
```
Application: radeon-profile (radeon-profile), signal: Segmentation fault
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f4959e5d800 (LWP 4963))]

Thread 10 (Thread 0x7f4939ffb700 (LWP 4973)):
#0  0x00007f4959777415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f4945bdb72c in ?? () from /usr/lib/dri/radeonsi_dri.so
#2  0x00007f4945bdb328 in ?? () from /usr/lib/dri/radeonsi_dri.so
#3  0x00007f495977157f in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f495934c0e3 in clone () from /usr/lib/libc.so.6

Thread 9 (Thread 0x7f493a7fc700 (LWP 4972)):
#0  0x00007f4959777415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f4945bdb72c in ?? () from /usr/lib/dri/radeonsi_dri.so
#2  0x00007f4945bdb328 in ?? () from /usr/lib/dri/radeonsi_dri.so
#3  0x00007f495977157f in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f495934c0e3 in clone () from /usr/lib/libc.so.6

Thread 8 (Thread 0x7f493affd700 (LWP 4971)):
#0  0x00007f4959777415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f4945bdb72c in ?? () from /usr/lib/dri/radeonsi_dri.so
#2  0x00007f4945bdb328 in ?? () from /usr/lib/dri/radeonsi_dri.so
#3  0x00007f495977157f in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f495934c0e3 in clone () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7f493b7fe700 (LWP 4970)):
#0  0x00007f4959777415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f4945bdb72c in ?? () from /usr/lib/dri/radeonsi_dri.so
#2  0x00007f4945bdb328 in ?? () from /usr/lib/dri/radeonsi_dri.so
#3  0x00007f495977157f in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f495934c0e3 in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7f493bfff700 (LWP 4969)):
#0  0x00007f4959777415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f4945bdb72c in ?? () from /usr/lib/dri/radeonsi_dri.so
#2  0x00007f4945bdb328 in ?? () from /usr/lib/dri/radeonsi_dri.so
#3  0x00007f495977157f in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f495934c0e3 in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7f4940e9f700 (LWP 4968)):
#0  0x00007f4959777415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f4945bdb72c in ?? () from /usr/lib/dri/radeonsi_dri.so
#2  0x00007f4945bdb328 in ?? () from /usr/lib/dri/radeonsi_dri.so
#3  0x00007f495977157f in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f495934c0e3 in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7f4947d7f700 (LWP 4967)):
#0  0x00007f4959777415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f4945bdb72c in ?? () from /usr/lib/dri/radeonsi_dri.so
#2  0x00007f4945bdb328 in ?? () from /usr/lib/dri/radeonsi_dri.so
#3  0x00007f495977157f in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f495934c0e3 in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7f494cf1d700 (LWP 4966)):
#0  0x00007f49582eb4e4 in g_mutex_unlock () from /usr/lib/libglib-2.0.so.0
#1  0x00007f495833aa75 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007f495833ab51 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007f4959a779bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#4  0x00007f4959a1e5ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#5  0x00007f49598512f5 in QThread::exec() () from /usr/lib/libQt5Core.so.5
#6  0x00007f49559edb37 in ?? () from /usr/lib/libQt5DBus.so.5
#7  0x00007f4959852520 in ?? () from /usr/lib/libQt5Core.so.5
#8  0x00007f495977157f in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007f495934c0e3 in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7f4954c17700 (LWP 4965)):
#0  0x00007f4959341667 in poll () from /usr/lib/libc.so.6
#1  0x00007f4959204630 in ?? () from /usr/lib/libxcb.so.1
#2  0x00007f49592062db in xcb_wait_for_event () from /usr/lib/libxcb.so.1
#3  0x00007f4955b2b049 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#4  0x00007f4959852520 in ?? () from /usr/lib/libQt5Core.so.5
#5  0x00007f495977157f in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f495934c0e3 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f4959e5d800 (LWP 4963)):
[KCrash Handler]
#6  0x00007f49598d26a1 in QString::append(QString const&) () from /usr/lib/libQt5Core.so.5
#7  0x000055957783e6d6 in ?? ()
#8  0x0000559577835a8a in ?? ()
#9  0x0000559577888d7e in ?? ()
#10 0x00007f4959a4ba11 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#11 0x00007f495a69a663 in QAbstractButton::clicked(bool) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007f495a69a88c in ?? () from /usr/lib/libQt5Widgets.so.5
#13 0x00007f495a69bc92 in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007f495a69be56 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007f495a5e4cb6 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007f495a5a14d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007f495a5aac6c in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007f4959a1f9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#19 0x00007f495a5a9d4b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007f495a601211 in ?? () from /usr/lib/libQt5Widgets.so.5
#21 0x00007f495a604154 in ?? () from /usr/lib/libQt5Widgets.so.5
#22 0x00007f495a5a14d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#23 0x00007f495a5aaa21 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#24 0x00007f4959a1f9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#25 0x00007f4959f81789 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#26 0x00007f4959f8305b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#27 0x00007f4959f5b37c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#28 0x00007f4955b2bfec in ?? () from /usr/lib/libQt5XcbQpa.so.5
#29 0x00007f4958338cf4 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#30 0x00007f495833ab11 in ?? () from /usr/lib/libglib-2.0.so.0
#31 0x00007f495833ab51 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#32 0x00007f4959a779a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#33 0x00007f4959a1e5ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#34 0x00007f4959a26326 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#35 0x0000559577809f3f in ?? ()
#36 0x00007f4959276ee3 in __libc_start_main () from /usr/lib/libc.so.6
#37 0x000055957780ab3e in ?? ()
[Inferior 1 (process 4963) detached]

```
The software did not display any information and then stopped.

**Comment by Oxalin** [comment]
Is it reproducible?
