### ISSUE TITLE
Crash upon closing, in QChart destructor

### ISSUE THREAD

**Issue by j1elo** [marazmista/radeon-profile#196]
Seems like some memory is not being correctly handled and the destructor causes an invalid access when the application is closed. Reproducible every time.

Version info:
* Linux Mint 18.3 Sylvia (equals to Ubuntu 16.04 Xenial)
* Qt 5.14.2 (official offline installer from qt.io)
* GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Build & run steps**:
```
# Download, install & configure standalone Qt ...
# ./qt-opensource-linux-x64-5.14.2.run

sudo apt-get update && sudo apt-get install --no-install-recommends --yes \
    libdrm-dev \
    libxrandr-dev \
    mesa-utils \
    qt5-default \
    x11-utils \
    x11-xserver-utils

git clone https://github.com/marazmista/radeon-profile.git
cd radeon-profile/radeon-profile/
qmake -qt=qt5.14 CONFIG+=debug
make

sudo gdb ./target/radeon-profile
```

**Full output log**:
Attached file "radeon-profile.log"

**GDB backtrace**:
```
(gdb) bt
#0  0x00007ffff4921428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff492302a in __GI_abort () at abort.c:89
#2  0x00007ffff49637ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff4a7ced8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff4970698 in malloc_printerr (ar_ptr=0x0, ptr=<optimized out>, str=0x7ffff4a7cf00 "munmap_chunk(): invalid pointer", action=<optimized out>) at malloc.c:5006
#4  munmap_chunk (p=<optimized out>) at malloc.c:2842
#5  __GI___libc_free (mem=<optimized out>) at malloc.c:2963
#6  0x00007ffff7577f31 in QtCharts::ChartDataSet::deleteAllSeries() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Charts.so.5
#7  0x00007ffff7578397 in QtCharts::ChartDataSet::~ChartDataSet() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Charts.so.5
#8  0x00007ffff75783c9 in QtCharts::ChartDataSet::~ChartDataSet() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Charts.so.5
#9  0x00007ffff75830ff in QtCharts::QChart::~QChart() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Charts.so.5
#10 0x0000000000423b06 in PieProgressBar::~PieProgressBar (this=0xf73700, __in_chrg=<optimized out>) at components/pieprogressbar.h:39
#11 0x000000000044a59f in PieItem::~PieItem (this=0xf73700, __in_chrg=<optimized out>) at components/topbarcomponents.h:125
#12 0x000000000044a5e4 in PieItem::~PieItem (this=0xf73700, __in_chrg=<optimized out>) at components/topbarcomponents.h:125
#13 0x00007ffff5a96603 in QObjectPrivate::deleteChildren() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Core.so.5
#14 0x00007ffff6e141e7 in QWidget::~QWidget() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Widgets.so.5
#15 0x00007ffff6e143d9 in QWidget::~QWidget() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Widgets.so.5
#16 0x00007ffff5a96603 in QObjectPrivate::deleteChildren() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Core.so.5
#17 0x00007ffff6e141e7 in QWidget::~QWidget() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Widgets.so.5
#18 0x00007ffff6e143d9 in QWidget::~QWidget() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Widgets.so.5
#19 0x00007ffff5a96603 in QObjectPrivate::deleteChildren() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Core.so.5
#20 0x00007ffff6e141e7 in QWidget::~QWidget() () from /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Widgets.so.5
#21 0x000000000041ad9a in radeon_profile::~radeon_profile (this=0x7fffffffe220, __in_chrg=<optimized out>) at radeon_profile.cpp:69
#22 0x0000000000419ba1 in main (argc=1, argv=0x7fffffffe4c8) at main.cpp:24
```

**Comment by marazmista** [comment]
Fixed in commit: d17fb902779841a2a399e82c8dc5820800a964fe
