### ISSUE TITLE
Segmentation fault when running radeon-profile as a regular user and running the daemon as root at the same time

### ISSUE THREAD

**Issue by haadr** [marazmista/radeon-profile#244]
```


$ qmake-qt5 --version
QMake version 3.1
Using Qt version 5.15.2 in /usr/lib64
```
radeon-profile commit: 0fd5b8dd326957e6fa8afda2bba5fc4c48fd0de4

Using amdgpu, kernel  5.10.0-rc6

**Problem**

When running the radeon-profile-daemon commit 7923bd62df3ab2c5c355e4085613895bfaa774fe, running radeon-profile as a regular user leads to a segfault. Stopping radeon-profile-daemon will make it not crash, it just won't display anything.

Running radeon-profile as root, while running radeon-profile-daemon, works.

Gdb backtrace:

```
#0  0x00007ffff68aaea4 in QString::trimmed_helper(QString const&) () from /usr/lib64/libQt5Core.so.5
#1  0x000000000044bb36 in gpu::detectCards() ()
#2  0x000000000044c496 in gpu::initialize(dXorg::InitializationConfig const&) ()
#3  0x0000000000429f06 in radeon_profile::initializeDevice() ()
#4  0x000000000042a541 in radeon_profile::daemonConnected() ()
#5  0x00007ffff6a3d8a0 in ?? () from /usr/lib64/libQt5Core.so.5
#6  0x00007ffff6df8755 in ?? () from /usr/lib64/libQt5Network.so.5
#7  0x00000000004657c3 in DaemonComm::connectToDaemon() ()
#8  0x000000000042a479 in radeon_profile::radeon_profile(QWidget*) ()
#9  0x0000000000422f95 in main ()
```

Edit:

Looks like `globalStuff::grabSystemInfo("lspci -s " + ueventContents[pciIdx].split('=')` returns a list of 1 element, which is empty. The input to grabSystemInfo is `lspci -s 0000:01:00.0` which when I run it manually returns `01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290/390]`.

Attached a fix to illustrate it, however I'd test for all those string operations to be sure.

[safety_ftw.txt](https://github.com/marazmista/radeon-profile/files/5639024/safety_ftw.txt)

**Comment by Polynomial-C** [comment]
Having the same issue on my Gentoo machines. Your patch fixes the issue for me.
