### ISSUE TITLE
Segfault - ASSERT failure in QList<T>::operator[]: "index out of range"

### ISSUE THREAD

**Issue by ganthore** [marazmista/radeon-profile#269]
Building off of the latest git commit: 0fd5b8dd326957e6fa8afda2bba5fc4c48fd0de4
Distro: Arch
Kernel: 5.12.3
QT: 5.15.2
Card: Radeon 6800 XT (Sapphire Nitro+)

radeon-profile will segfault when executed. I re-compiled the binary with debugging enabled and was able to capture more details.

```
gdb radeon-profile
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from radeon-profile...
(No debugging symbols found in radeon-profile)
(gdb) run
Starting program: /usr/bin/radeon-profile 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Creating application object
[New Thread 0x7ffff2d21640 (LWP 112957)]
Creating radeon_profile
[New Thread 0x7fffe0548640 (LWP 112958)]
[New Thread 0x7fffdfd47640 (LWP 112959)]
[New Thread 0x7fffdf546640 (LWP 112960)]
[New Thread 0x7fffded45640 (LWP 112961)]
[New Thread 0x7fffde544640 (LWP 112962)]
[New Thread 0x7fffddd43640 (LWP 112963)]
[New Thread 0x7fffdd542640 (LWP 112964)]
[New Thread 0x7fffdcd41640 (LWP 112965)]
[New Thread 0x7fffb7fff640 (LWP 112966)]
[New Thread 0x7fffbffff640 (LWP 112967)]
[New Thread 0x7fffbf7fe640 (LWP 112968)]
[New Thread 0x7fffbeffd640 (LWP 112969)]
[New Thread 0x7fffbe7fc640 (LWP 112970)]
Loading configuration
Creating ui elements
[New Thread 0x7fffbdffb640 (LWP 112971)]
[New Thread 0x7fffb5d3b640 (LWP 112972)]
[New Thread 0x7fffb553a640 (LWP 112973)]
[New Thread 0x7fffb4d39640 (LWP 112974)]
[New Thread 0x7fff9a5a0640 (LWP 112975)]
[New Thread 0x7fff99d9f640 (LWP 112976)]
[New Thread 0x7fff9959e640 (LWP 112977)]
[New Thread 0x7fff98d9d640 (LWP 112978)]
[New Thread 0x7fff7bfff640 (LWP 112979)]
[New Thread 0x7fff7b7fe640 (LWP 112980)]
[New Thread 0x7fff7affd640 (LWP 112981)]
[New Thread 0x7fff7a7fc640 (LWP 112982)]
[New Thread 0x7fff79ffb640 (LWP 112983)]
[New Thread 0x7fff797fa640 (LWP 112984)]
[New Thread 0x7fff78ff9640 (LWP 112985)]
[New Thread 0x7fff57fff640 (LWP 112986)]
[New Thread 0x7fff577fe640 (LWP 112987)]
[New Thread 0x7fff56ffd640 (LWP 112988)]
Icon theme "gnome" not found.
[Detaching after fork from child process 112989]
Analyzing screen  0
  Analyzing output  0
    Analyzing active mode
      Property is EDID, parsing it
Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.
Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.
Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.
Searching PnP ID:  "AUS"
  Analyzing output  1
    Analyzing active mode
      Property is EDID, parsing it
Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.
Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.
Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.
Searching PnP ID:  "ACI"
Found PnP ID:  "ACI" -> "Ancor Communications Inc"
  Analyzing output  2
  Analyzing output  3
[Detaching after fork from child process 112990]
Connecting to daemon...
Daemon connected
Initializing device
[Detaching after fork from child process 112991]
[Detaching after fork from child process 112992]
Card detected:
 module:  "amdgpu" 
 sysName(path):  "card0" 
 name:  "UNKNOWN"
[Detaching after fork from child process 112993]
hwmon path:  "/sys/class/drm/card0/device/hwmon/hwmon3/"
Opened /dev/dri/renderD128 , fd number: 29
QFSFileEngine::open: No file name specified
Detected power method based on sysfs power_method file: 3
Power method: Power Profile Modes. Creating profiles list
ioctlHandler: everything ok
ASSERT failure in QList<T>::operator[]: "index out of range", file /usr/include/qt/QtCore/qlist.h, line 579

Thread 1 "radeon-profile" received signal SIGABRT, Aborted.
0x00007ffff62d7ef5 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff62d7ef5 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff62c1862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff68dd9ac in QMessageLogger::fatal(char const*, ...) const () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff68dcdb6 in qt_assert_x(char const*, char const*, char const*, int) () from /usr/lib/libQt5Core.so.5
#4  0x000055555559510b in ?? ()
#5  0x00005555555b5383 in ?? ()
#6  0x00005555555b56eb in ?? ()
#7  0x00005555555b39b7 in ?? ()
#8  0x00005555555ae394 in ?? ()
#9  0x00005555555ae174 in ?? ()
#10 0x00005555555a356b in ?? ()
#11 0x000055555557270d in ?? ()
#12 0x0000555555572942 in ?? ()
#13 0x00005555555eebb8 in ?? ()
#14 0x00007ffff6b3abb0 in ?? () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff6e93987 in ?? () from /usr/lib/libQt5Network.so.5
#16 0x00005555555c7521 in ?? ()
#17 0x0000555555572328 in ?? ()
#18 0x0000555555571447 in ?? ()
#19 0x00007ffff62c2b25 in __libc_start_main () from /usr/lib/libc.so.6
#20 0x0000555555570cae in ?? ()
(gdb) continue
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) [Thread 0x7fff56ffd640 (LWP 112988) exited]
[Thread 0x7fff577fe640 (LWP 112987) exited]
[Thread 0x7fff57fff640 (LWP 112986) exited]
[Thread 0x7fff78ff9640 (LWP 112985) exited]
[Thread 0x7fff797fa640 (LWP 112984) exited]
[Thread 0x7fff79ffb640 (LWP 112983) exited]
[Thread 0x7fff7a7fc640 (LWP 112982) exited]
[Thread 0x7fff7affd640 (LWP 112981) exited]
[Thread 0x7fff7b7fe640 (LWP 112980) exited]
[Thread 0x7fff7bfff640 (LWP 112979) exited]
[Thread 0x7fff98d9d640 (LWP 112978) exited]
[Thread 0x7fff9959e640 (LWP 112977) exited]
[Thread 0x7fff99d9f640 (LWP 112976) exited]
[Thread 0x7fff9a5a0640 (LWP 112975) exited]
[Thread 0x7fffb4d39640 (LWP 112974) exited]
[Thread 0x7fffb553a640 (LWP 112973) exited]
[Thread 0x7fffb5d3b640 (LWP 112972) exited]
[Thread 0x7fffbdffb640 (LWP 112971) exited]
[Thread 0x7fffbe7fc640 (LWP 112970) exited]
[Thread 0x7fffbeffd640 (LWP 112969) exited]
[Thread 0x7fffbf7fe640 (LWP 112968) exited]
[Thread 0x7fffbffff640 (LWP 112967) exited]
[Thread 0x7fffb7fff640 (LWP 112966) exited]
[Thread 0x7fffdcd41640 (LWP 112965) exited]
[Thread 0x7fffdd542640 (LWP 112964) exited]
[Thread 0x7fffddd43640 (LWP 112963) exited]
[Thread 0x7fffde544640 (LWP 112962) exited]
[Thread 0x7fffded45640 (LWP 112961) exited]
[Thread 0x7fffdf546640 (LWP 112960) exited]
[Thread 0x7fffdfd47640 (LWP 112959) exited]
[Thread 0x7fffe0548640 (LWP 112958) exited]
[Thread 0x7ffff2d21640 (LWP 112957) exited]

Program terminated with signal SIGABRT, Aborted.
The program no longer exists.
```

**Comment by Oxalin** [comment]
Could you test my forks of Radeon profile and Radeon profile daemon (you must use both or it won't work because the daemon's socket was modified)?

I merged the patches from emerge-e-world in my own fork and I'm building toward a new release from there.

Radeon Profile: https://github.com/Oxalin/radeon-profile
Radeon Profile daemon: https://github.com/Oxalin/radeon-profile-daemon
